### ISSUE TITLE
App crashes if DayZ profile directory doesn't exist

### ISSUE THREAD

**Issue by tjensen** [tjensen/DayZServerMonitor#4]
If the DayZ profile folder (usually, `%USERPROFILE%\Documents\DayZ`) does not exist when the user launches the program, it crashes immediately:

```
Application: DayZServerMonitor.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at System.IO.FileSystemWatcher..ctor(System.String, System.String)
   at DayZServerMonitorCore.ProfileWatcher..ctor(System.String, System.String, System.ComponentModel.ISynchronizeInvoke, System.Action)
   at DayZServerMonitor.DayZServerMonitorForm.Initialize()
   at DayZServerMonitor.Program.Main()
```

If the profile folder doesn't exist, the app should still run, although it won't be very useful since it won't be able to read the most recent server address. That should improve when #1 is implemented.

Failure to set up the profile watcher should send the error to the error log when #2 is implemented. However, the app should also provide some easily visible indication in the main UI that the profile watcher failed, per #3.

**Comment by tjensen** [comment]
Fixed in [v1.0.1.30](https://github.com/tjensen/DayZServerMonitor/releases/tag/v1.0.1.30).
